apiVersion: v1
kind: Pod
metadata:
  name: service-catalog-apiserver
  labels:
    app: apiserver
spec:
  containers:
  - name: apiserver
    image: apiserver
    imagePullPolicy: IfNotPresent
    args: 
    - --etcd-servers
    - http://localhost:2379
    - -v
    - "10"
    ports:
    - name: https
      containerPort: 6443
  - name: etcd
    image: gcr.io/google_containers/etcd:3.0.14
    command: ["etcd"]
---
apiVersion: v1
kind: Service
metadata:
  name: service-catalog-apiserver
spec:
  selector:
    app: apiserver
  ports:
  - protocol: TCP
    port: 6443
    targetPort: https

